#!/usr/bin/env php
<?php
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Debug\Debug;

set_time_limit(0);
require 'autoload.php';
Debug::enable();
$application = new Application(new AppKernel);
$application->run();
